import os
from datetime import datetime, timedelta
from decimal import Decimal

from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from app.database.db import SessionLocal
from app.database.models import (
    Bill,
    BillItem,
    Product
)


GENERATED_DIR = "generated"


def _date_range(days):
    """
    Return start and end timestamps.
    """

    end = datetime.now()
    start = end - timedelta(days=days)

    return start, end


def _get_finalized_bills(
    db,
    start,
    end
):
    """
    Retrieve finalized bills in date range.
    """

    return (
        db.query(Bill)
        .filter(
            Bill.status == "finalized",
            Bill.created_at >= start,
            Bill.created_at <= end
        )
        .order_by(Bill.created_at.asc())
        .all()
    )


def _calculate_sales_data(bills):
    """
    Calculate sales metrics.
    """

    total_sales = Decimal("0.00")
    total_gst = Decimal("0.00")

    payment_totals = {
        "cash": Decimal("0.00"),
        "upi": Decimal("0.00"),
        "card": Decimal("0.00"),
        "credit": Decimal("0.00")
    }

    daily_sales = {}

    for bill in bills:

        total = Decimal(
            str(bill.total_amount)
        )

        gst = Decimal(
            str(bill.gst_amount)
        )

        total_sales += total
        total_gst += gst

        payment_mode = (
            bill.payment_mode
            or "unknown"
        ).lower()

        if payment_mode in payment_totals:

            payment_totals[payment_mode] += total

        date_key = bill.created_at.strftime(
            "%Y-%m-%d"
        )

        daily_sales.setdefault(
            date_key,
            Decimal("0.00")
        )

        daily_sales[date_key] += total

    return {
        "total_sales": total_sales,
        "total_gst": total_gst,
        "payment_totals": payment_totals,
        "daily_sales": daily_sales
    }


def _get_top_products(
    db,
    bills
):
    """
    Find top-selling products by quantity.
    """

    quantities = {}

    for bill in bills:

        for item in bill.items:

            product = (
                db.query(Product)
                .filter(
                    Product.id == item.product_id
                )
                .first()
            )

            if not product:
                continue

            name = product.name

            quantities.setdefault(
                name,
                Decimal("0")
            )

            quantities[name] += Decimal(
                str(item.quantity)
            )

    return sorted(
        quantities.items(),
        key=lambda x: x[1],
        reverse=True
    )[:10]


def _get_inventory_data(db):
    """
    Calculate inventory health.
    """

    products = (
        db.query(Product)
        .order_by(Product.name.asc())
        .all()
    )

    healthy = 0
    low = 0
    out_of_stock = 0

    for product in products:

        quantity = Decimal(
            str(product.quantity)
        )

        reorder_level = Decimal(
            str(product.reorder_level)
        )

        if quantity <= 0:

            out_of_stock += 1

        elif quantity <= reorder_level:

            low += 1

        else:

            healthy += 1

    return {
        "healthy": healthy,
        "low": low,
        "out_of_stock": out_of_stock,
        "total": len(products)
    }


def _add_title(slide, title):
    """
    Add slide title.
    """

    textbox = slide.shapes.add_textbox(
        Inches(0.6),
        Inches(0.25),
        Inches(12),
        Inches(0.7)
    )

    frame = textbox.text_frame

    paragraph = frame.paragraphs[0]

    paragraph.text = title
    paragraph.font.size = Pt(24)
    paragraph.font.bold = True


def _add_footer(slide):
    """
    Add footer.
    """

    textbox = slide.shapes.add_textbox(
        Inches(0.6),
        Inches(7.05),
        Inches(12),
        Inches(0.25)
    )

    paragraph = (
        textbox
        .text_frame
        .paragraphs[0]
    )

    paragraph.text = (
        "Generated by Nebula Supermarket Ops Agent"
    )

    paragraph.font.size = Pt(8)
    paragraph.alignment = PP_ALIGN.CENTER


def _add_bullet_text(
    slide,
    lines,
    left=0.8,
    top=1.4,
    width=11.5,
    height=4.8
):
    """
    Add bullet list.
    """

    textbox = slide.shapes.add_textbox(
        Inches(left),
        Inches(top),
        Inches(width),
        Inches(height)
    )

    frame = textbox.text_frame
    frame.clear()

    for index, line in enumerate(lines):

        if index == 0:

            paragraph = frame.paragraphs[0]

        else:

            paragraph = frame.add_paragraph()

        paragraph.text = line
        paragraph.font.size = Pt(18)
        paragraph.space_after = Pt(12)


def generate_analysis_deck(days=7):
    """
    Generate a PowerPoint business analysis deck
    with real PowerPoint charts.
    """

    db = SessionLocal()

    try:

        os.makedirs(
            GENERATED_DIR,
            exist_ok=True
        )

        start, end = _date_range(
            days
        )

        bills = _get_finalized_bills(
            db,
            start,
            end
        )

        sales_data = _calculate_sales_data(
            bills
        )

        top_products = _get_top_products(
            db,
            bills
        )

        inventory = _get_inventory_data(
            db
        )

        prs = Presentation()

        # ==================================================
        # SLIDE 1 — TITLE
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        textbox = slide.shapes.add_textbox(
            Inches(1),
            Inches(2.1),
            Inches(11),
            Inches(1.2)
        )

        paragraph = (
            textbox
            .text_frame
            .paragraphs[0]
        )

        paragraph.text = (
            "NEBULA SUPERMARKET"
        )

        paragraph.font.size = Pt(34)
        paragraph.font.bold = True
        paragraph.alignment = PP_ALIGN.CENTER

        textbox2 = slide.shapes.add_textbox(
            Inches(1),
            Inches(3.4),
            Inches(11),
            Inches(1)
        )

        paragraph2 = (
            textbox2
            .text_frame
            .paragraphs[0]
        )

        paragraph2.text = (
            f"{days}-Day Business Analysis"
        )

        paragraph2.font.size = Pt(24)
        paragraph2.alignment = PP_ALIGN.CENTER

        _add_footer(slide)

        # ==================================================
        # SLIDE 2 — SALES SUMMARY
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Sales Summary"
        )

        avg_bill = (
            sales_data["total_sales"]
            / len(bills)
            if bills
            else Decimal("0.00")
        )

        lines = [
            f"Total sales: ₹{sales_data['total_sales']:.2f}",
            f"GST collected: ₹{sales_data['total_gst']:.2f}",
            f"Number of bills: {len(bills)}",
            f"Average bill value: ₹{avg_bill:.2f}",
            f"Products tracked: {inventory['total']}",
            f"Low-stock products: {inventory['low']}",
            f"Out-of-stock products: {inventory['out_of_stock']}"
        ]

        _add_bullet_text(
            slide,
            lines
        )

        _add_footer(slide)

        # ==================================================
        # SLIDE 3 — DAILY SALES CHART
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Daily Sales"
        )

        chart_data = ChartData()

        daily = sales_data[
            "daily_sales"
        ]

        if daily:

            chart_data.categories = list(
                daily.keys()
            )

            chart_data.add_series(
                "Sales",
                [
                    float(value)
                    for value in daily.values()
                ]
            )

        else:

            chart_data.categories = [
                "No sales"
            ]

            chart_data.add_series(
                "Sales",
                [0]
            )

        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED,
            Inches(0.8),
            Inches(1.3),
            Inches(11.5),
            Inches(5.2),
            chart_data
        ).chart

        chart.has_legend = False
        chart.has_title = True
        chart.chart_title.text_frame.text = (
            "Sales by Day"
        )

        chart.value_axis.has_major_gridlines = True

        _add_footer(slide)

        # ==================================================
        # SLIDE 4 — PAYMENT CHART
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Payment Mode Breakdown"
        )

        payment_data = ChartData()

        payment_data.categories = [
            "Cash",
            "UPI",
            "Card",
            "Credit"
        ]

        payment_data.add_series(
            "Amount",
            [
                float(
                    sales_data["payment_totals"]["cash"]
                ),
                float(
                    sales_data["payment_totals"]["upi"]
                ),
                float(
                    sales_data["payment_totals"]["card"]
                ),
                float(
                    sales_data["payment_totals"]["credit"]
                )
            ]
        )

        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.PIE,
            Inches(2),
            Inches(1.4),
            Inches(8.5),
            Inches(5),
            payment_data
        ).chart

        chart.has_legend = True
        chart.has_title = True
        chart.chart_title.text_frame.text = (
            "Sales by Payment Mode"
        )

        _add_footer(slide)

        # ==================================================
        # SLIDE 5 — TOP PRODUCTS
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Top Selling Products"
        )

        product_data = ChartData()

        if top_products:

            product_data.categories = [
                item[0]
                for item in top_products
            ]

            product_data.add_series(
                "Quantity",
                [
                    float(item[1])
                    for item in top_products
                ]
            )

        else:

            product_data.categories = [
                "No sales"
            ]

            product_data.add_series(
                "Quantity",
                [0]
            )

        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.BAR_CLUSTERED,
            Inches(1),
            Inches(1.2),
            Inches(11),
            Inches(5.5),
            product_data
        ).chart

        chart.has_legend = False
        chart.has_title = True
        chart.chart_title.text_frame.text = (
            "Top Products by Quantity Sold"
        )

        _add_footer(slide)

        # ==================================================
        # SLIDE 6 — INVENTORY HEALTH
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Inventory Health"
        )

        inventory_data = ChartData()

        inventory_data.categories = [
            "Healthy",
            "Low Stock",
            "Out of Stock"
        ]

        inventory_data.add_series(
            "Products",
            [
                inventory["healthy"],
                inventory["low"],
                inventory["out_of_stock"]
            ]
        )

        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.DOUGHNUT,
            Inches(2),
            Inches(1.4),
            Inches(8.5),
            Inches(5),
            inventory_data
        ).chart

        chart.has_legend = True
        chart.has_title = True
        chart.chart_title.text_frame.text = (
            "Inventory Status"
        )

        _add_footer(slide)

        # ==================================================
        # SLIDE 7 — INSIGHTS
        # ==================================================

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        _add_title(
            slide,
            "Business Insights"
        )

        insights = []

        if inventory["out_of_stock"] > 0:

            insights.append(
                f"{inventory['out_of_stock']} "
                "products are out of stock and need replenishment."
            )

        if inventory["low"] > 0:

            insights.append(
                f"{inventory['low']} products are at or below "
                "their reorder level."
            )

        if top_products:

            insights.append(
                f"Top-selling product: "
                f"{top_products[0][0]}."
            )

        if sales_data["total_sales"] > 0:

            insights.append(
                f"Total revenue for the selected period "
                f"was ₹{sales_data['total_sales']:.2f}."
            )

            insights.append(
                f"GST collected was "
                f"₹{sales_data['total_gst']:.2f}."
            )

        if not insights:

            insights.append(
                "No finalized sales were recorded "
                "during the selected period."
            )

        _add_bullet_text(
            slide,
            insights
        )

        _add_footer(slide)

        # ==================================================
        # SAVE
        # ==================================================

        filename = (
            f"analysis_deck_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        )

        filepath = os.path.join(
            GENERATED_DIR,
            filename
        )

        prs.save(
            filepath
        )

        return {
            "success": True,
            "filepath": filepath,
            "filename": filename,
            "days": days,
            "bill_count": len(bills),
            "total_sales": float(
                sales_data["total_sales"]
            ),
            "gst_collected": float(
                sales_data["total_gst"]
            ),
            "top_products": [
                {
                    "product": name,
                    "quantity": float(quantity)
                }
                for name, quantity
                in top_products
            ],
            "inventory": inventory,
            "message": (
                "Business analysis PowerPoint generated "
                "successfully with real charts."
            )
        }

    except Exception as e:

        return {
            "success": False,
            "message": (
                f"Error generating analysis deck: {str(e)}"
            )
        }

    finally:

        db.close()